name: CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build the project
        run: gradlew.bat assemble

      - name: Run tests
        run: gradlew.bat test
